---
title: "HW4 Almond Profit & Sensitivity Test"
format: html
author: Henry Oliver and Sofia Rodas
date: January 28, 2026
---

This quarto document 
```{r}
# load necessary libraries
library(tidyverse)
library(here)
library(janitor)
library(purrr)
```

```{r}
# read in data
clim_data <- read.table(here("Data", "clim.txt"),
                        header = TRUE, 
                        sep = " ")

# source the functions
source(here("Assignments/henry_assignment_4/almond_yield.R"))
source(here("Assignments/henry_assignment_4/revenue_npv.R"))
source(here("Assignments/henry_assignment_4/cost_npv.R"))
source(here("Assignments/henry_assignment_4/almond_profit.R"))
```

```{r}
# Get almond yield df
almond_yield <- crop_yield(
  clim_data = clim_data,
  month = month,
  year = year,
  min_temp = tmin_c,
  precip = precip
)

```


```{r}
# Get almond profit df
almond_profit_df <- almond_profit(
  yield_df = almond_yield,
  base_price = 500, # Price per ton of almonds, scales with inflation
  base_cost = 1000, # Fixed cost - does not change with yield, does change with inflation
  inflation_rate = 0.03,
  discount_rate = 0.12
)
```


# Sensitivity test
## Analysis on base price and inflation

Create the values for the sensitivity test.
```{r}
# make the varied price values
var_base_price <- tibble(var_base_price = seq(from = 100, to = 800, by = 50))

# add the varied price values to the almond yield data frame
price_senstest <- expand_grid(almond_yield, var_base_price)
```

```{r}
# make the varied inflation rates
var_inflation <- tibble(var_inflation = seq(from = 0.01, to = 0.7, by = 0.06))

# add the varied inflation rates to the price_senstest data frame
price_inflation_senstest <- expand_grid(price_senstest, var_inflation)
```

```{r}
# Get almond profit df
almond_profit_senstest <- almond_profit(
  yield_df = price_inflation_senstest,
  base_price = price_inflation_senstest$var_base_price, # Price per ton of almonds, scales with inflation
  base_cost = 1000, # Fixed cost - does not change with yield, does change with inflation
  inflation_rate = price_inflation_senstest$var_inflation,
  discount_rate = 0.12
)
```

Then, plot to visualize the data
```{r}
ggplot(almond_profit_senstest, aes(x = var_inflation, 
                                     y = profit_npv, 
                                     col = var_base_price)) +
  geom_point(cex = 2, alpha = 0.5) +
  scale_color_viridis_c() +
  labs(x = "Inflation rate",
       y = "Profit  NPV",
       title = "Inflation rate influence on profit NPV") +
  theme_minimal()
```

```{r}
ggplot(almond_profit_senstest, aes(x = var_base_price, 
                                     y = profit_npv, 
                                     col = var_inflation)) +
  geom_point(cex = 2, alpha = 0.5) +
  scale_color_viridis_c() + 
  labs(x = "Base price",
       y = "Profit  NPV",
       title = "Base costs effect on profit NPV") +
  theme_minimal()
```



